version: '3.3'

services:
  nginx:
    image: nginx:1.13.8
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx

  backend:
    image: backend
    build: backend
    env_file: .env
    volumes:
      - ./backend/code:/code

  websockets:
    image: backend
    env_file: .env
    command: /code/scripts/start_webcokets
    volumes:
      - ./backend/code:/code

  frontend:
    build: frontend
    env_file: .env
    volumes:
      - ./frontend/code:/code
    command: npm run dev

  postgres:
    image: postgres:10.1
    env_file: .env
    labels:
      - "traefik.enable=false"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.7.5-management
    ports:
      - "15672:15672"

  redis:
    image: redis:3.2.11

  broadcaster:
    image: backend
    env_file: .env
    command: /code/scripts/start_broadcaster
    volumes:
      - ./backend/code:/code

  s1:
    image: backend
    env_file: .env
    command: /code/scripts/start_s1
    volumes:
      - ./backend/code:/code

  s2:
    image: backend
    env_file: .env
    command: /code/scripts/start_s2
    volumes:
      - ./backend/code:/code

  gateway:
    image: backend
    env_file: .env
    command: /code/scripts/start_gateway
    volumes:
      - ./backend/code:/code

volumes:
  postgres-data:
