"""add owner to game model

Revision ID: 0fecff35ad1a
Revises: b646bba0e7a8
Create Date: 2018-05-03 14:16:40.507961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fecff35ad1a'
down_revision = 'b646bba0e7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_games_owner_id_users'), 'games', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_games_owner_id_users'), 'games', type_='foreignkey')
    op.drop_column('games', 'owner_id')
    # ### end Alembic commands ###
