"""contests models

Revision ID: 2127774fbe45
Revises: 4573cfbb184e
Create Date: 2018-03-19 20:27:09.007371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2127774fbe45'
down_revision = '4573cfbb184e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_contests_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contests'))
    )
    op.create_index(op.f('ix_contests_uuid'), 'contests', ['uuid'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['contests.id'], name=op.f('fk_questions_owner_id_contests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    op.create_index(op.f('ix_questions_category'), 'questions', ['category'], unique=False)
    op.create_index(op.f('ix_questions_uuid'), 'questions', ['uuid'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_answers_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_answers'))
    )
    op.create_index(op.f('ix_answers_uuid'), 'answers', ['uuid'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('uq_users_email', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_email', 'users', ['email'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_answers_uuid'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_uuid'), table_name='questions')
    op.drop_index(op.f('ix_questions_category'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_contests_uuid'), table_name='contests')
    op.drop_table('contests')
    # ### end Alembic commands ###
