"""add timestamps

Revision ID: 27816164fc0f
Revises: 008aa76af1c4
Create Date: 2018-04-16 19:07:19.716847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27816164fc0f'
down_revision = '008aa76af1c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('answers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('contests', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('contests', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('questions', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('questions', 'updated_at')
    op.drop_column('questions', 'created_at')
    op.drop_column('contests', 'updated_at')
    op.drop_column('contests', 'created_at')
    op.drop_column('answers', 'updated_at')
    op.drop_column('answers', 'created_at')
    # ### end Alembic commands ###
