"""add screen events

Revision ID: 2bd26347a72a
Revises: bac9f6144197
Create Date: 2018-05-19 09:54:58.108144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bd26347a72a'
down_revision = 'bac9f6144197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('screen_events', sa.Column('answer_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('screen_events', sa.Column('question_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('screen_events', sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_screen_events_team_id_teams'), 'screen_events', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('fk_screen_events_answer_id_answers'), 'screen_events', 'answers', ['answer_id'], ['id'])
    op.create_foreign_key(op.f('fk_screen_events_question_id_questions'), 'screen_events', 'questions', ['question_id'], ['id'])
    op.add_column('screens', sa.Column('answer_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('screens', sa.Column('question_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('screens', sa.Column('team_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(op.f('fk_screens_team_id_teams'), 'screens', 'teams', ['team_id'], ['id'])
    op.create_foreign_key(op.f('fk_screens_answer_id_answers'), 'screens', 'answers', ['answer_id'], ['id'])
    op.create_foreign_key(op.f('fk_screens_question_id_questions'), 'screens', 'questions', ['question_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_screens_question_id_questions'), 'screens', type_='foreignkey')
    op.drop_constraint(op.f('fk_screens_answer_id_answers'), 'screens', type_='foreignkey')
    op.drop_constraint(op.f('fk_screens_team_id_teams'), 'screens', type_='foreignkey')
    op.drop_column('screens', 'team_id')
    op.drop_column('screens', 'question_id')
    op.drop_column('screens', 'answer_id')
    op.drop_constraint(op.f('fk_screen_events_question_id_questions'), 'screen_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_screen_events_answer_id_answers'), 'screen_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_screen_events_team_id_teams'), 'screen_events', type_='foreignkey')
    op.drop_column('screen_events', 'team_id')
    op.drop_column('screen_events', 'question_id')
    op.drop_column('screen_events', 'answer_id')
    # ### end Alembic commands ###
