"""remove unused values from answer

Revision ID: 8741e1cef57f
Revises: d5ff0cf7e72a
Create Date: 2018-05-01 20:16:05.774895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8741e1cef57f'
down_revision = 'd5ff0cf7e72a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'index')
    op.drop_column('answers', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('answers', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
