"""add is_active

Revision ID: a25c60537021
Revises: 77429ff6684d
Create Date: 2018-06-01 15:31:09.704556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a25c60537021'
down_revision = '77429ff6684d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('contests', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('game_answers', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('games', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('questions', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('screen_events', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('screens', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('teams', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('teams', 'is_active')
    op.drop_column('screens', 'is_active')
    op.drop_column('screen_events', 'is_active')
    op.drop_column('questions', 'is_active')
    op.drop_column('games', 'is_active')
    op.drop_column('game_answers', 'is_active')
    op.drop_column('contests', 'is_active')
    op.drop_column('answers', 'is_active')
    # ### end Alembic commands ###
