"""Add Screen and events

Revision ID: bac9f6144197
Revises: 32038b09fa26
Create Date: 2018-05-18 11:59:46.598124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bac9f6144197'
down_revision = '32038b09fa26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screens',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('view', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_screens_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screens'))
    )
    op.create_index(op.f('ix_screens_game_id'), 'screens', ['game_id'], unique=False)
    op.create_table('screen_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('screen_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('view', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['screen_id'], ['screens.id'], name=op.f('fk_screen_events_screen_id_screens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screen_events'))
    )
    op.create_index('screen_event_index', 'screen_events', ['created_at', 'screen_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('screen_event_index', table_name='screen_events')
    op.drop_table('screen_events')
    op.drop_index(op.f('ix_screens_game_id'), table_name='screens')
    op.drop_table('screens')
    # ### end Alembic commands ###
