#!/bin/bash
# This script adds requiretment and send it to the requirements.txt
rm backend/code/rankor.egg-info
docker-compose build
docker-compose run --rm -u 0 backend ./scripts/add_req $1
docker-compose build
git checkout -- backend/code/rankor.egg-info
