#!/bin/bash
# This script adds requiretment and send it to the requirements.txt
rm backend/code/cashflow.egg-info
docker-compose build
docker-compose run --rm -u 0 backend ./scripts/add_req $1
docker-compose build
g c -- backend/code/cashflow.egg-info
